### ISSUE TITLE
Is this plugin available for iOS?

### ISSUE THREAD

**Issue by GreyGandalfGrey** [DrMoriarty/godot-firebase-cloudmessaging#2]
Hi, I am pretty sure is not compatible but I ask just in case, I need push notifications on iOS and I cannot find something, this is the closest I got

**Comment by martinpelli** [comment]
> Hi, I am pretty sure is not compatible but I ask just in case, I need push notifications on iOS and I cannot find something, this is the closest I got

Is not compatible I tried it. He said  that will be available soon.

**Comment by DrMoriarty** [comment]
@GreyGandalfGrey just released plugin for iOS
