### ISSUE TITLE
Godot 3.3 compatibility

### ISSUE THREAD

**Issue by martinpelli** [DrMoriarty/godot-firebase-cloudmessaging#3]
I tested the plugin on Godot 3.3 and is not working, that´s ok or I am making something wrong?

**Comment by martinpelli** [comment]
Fixed, if you want to go from 3.2.x to 3.3 just delete the Android folder, install Android templates again, and reinstall the plugin. I was doing that but when reinstalling the plugin when opening native lib windows the Firebase Cloud Messaging and Firebase Core were already installed, so I uninstalled and installed again and working.

**Comment by martinpelli** [comment]
@DrMoriarty Hi, I need iOS implementation or  I am going to die, so I am trying to implement it following the docs: https://firebase.google.com/docs/cloud-messaging/ios/client It´s all ok until come a part where you have to put some swift code to initialize the plugin, specifically on UIApplicationDelegate. When exporting with Godot there is no such file or any to add Swift code, do you have any knowledge, or reference, tutorial or anything that can allow me continue the implementation? Sorry to bother you it´s something very important to me.

**Comment by DrMoriarty** [comment]
@martinpelli HI!
I promised to make it for iOS. It mostly complete, today in the evening I will release it.

**Comment by DrMoriarty** [comment]
@martinpelli I just released FirebaseCloudMessaging and FirebaseAnalytics (cloud messages depends on it)
Test them please.

**Comment by martinpelli** [comment]
@DrMoriarty THANKSSSS!!! I am on it!

**Comment by martinpelli** [comment]
@DrMoriarty 
```
Godot Engine v3.3.stable.official - https://godotengine.org
2021-04-27 13:58:33.424057-0300 GoApps[8985:16701339] OpenGL ES 2.0 Renderer: Apple A11 GPU
2021-04-27 13:58:33.433961-0300 GoApps[8985:16701339] OpenGL ES Batching: ON
2021-04-27 13:58:33.760390-0300 GoApps[8985:16701339] 
2021-04-27 13:58:33.885966-0300 GoApps[8985:16701339] Initialize FirebaseAnalytics
2021-04-27 13:58:34.084820-0300 GoApps[8985:16701339] *** Terminating app due to uncaught exception 'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID. Please update your Firebase Instance ID version.'
*** First throw call stack:
(0x190ff69d8 0x1a5379b54 0x190ef94d0 0x101495144 0x10149428c 0x10149419c 0x101494020 0x101493f80 0x10149019c 0x101490354 0x10149072c 0x10149491c 0x1014948a4 0x10148c390 0x10148c2bc 0x10148d874 0x10148d554 0x10148ccc4 0x10148c93c 0x10148c8c8 0x1014873c0 0x1014885c4 0x10033f248 0x10033fb78 0x19412e640 0x194200a20 0x190f53b54 0x190f77420 0x190f76834 0x190f709f4 0x190f6fba0 0x1a7cd5598 0x1938612f4 0x193866874 0x100343868)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID. Please update your Firebase Instance ID version.'
terminating with uncaught exception of type NSException
(lldb) 
```

I made a clean install and putted the .plist file on my root Xcode project and got this

**Comment by DrMoriarty** [comment]
Do you use any additional firebase frameworks in your project?

**Comment by martinpelli** [comment]
> Do you use any additional firebase frameworks in your project?

No, I only use this plugin, no other plugin/framework/addon

**Comment by DrMoriarty** [comment]
I have no ideas what is wrong with it. In my test project this two plugins works as expected:
```
2021-04-28 10:40:34.362401+0300 nativelib-test[24133:33174649] Godot Engine v3.3.stable.custom_build.c157be8e6 - https://godotengine.org
Godot Engine v3.3.stable.custom_build.c157be8e6 - https://godotengine.org
2021-04-28 10:40:34.386899+0300 nativelib-test[24133:33174649] OpenGL ES 3.0 Renderer: Apple A8 GPU
OpenGL ES 3.0 Renderer: Apple A8 GPU
2021-04-28 10:40:34.398144+0300 nativelib-test[24133:33174649] OpenGL ES Batching: ON
OpenGL ES Batching: ON
2021-04-28 10:40:34.890546+0300 nativelib-test[24133:33174649] 
 
2021-04-28 10:40:35.338070+0300 nativelib-test[24133:33174649] Initialize FirebaseAnalytics
2021-04-28 10:40:35.503413+0300 nativelib-test[24133:33174932] 7.1.0 - [Firebase/Analytics][I-ACS023007] Analytics v.7.1.0 started
2021-04-28 10:40:35.505120+0300 nativelib-test[24133:33174932] 7.1.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-04-28 10:40:35.516914+0300 nativelib-test[24133:33174649] Initialize FirebaseCloudMessaging
```

Could you send me your iOS export?
(also tip: you can store your plist in your project `addons/nativelib-export/iOS`. The NativeLib-Export designed to process custom iOS export task like copying plists and resource bundles into export project)

**Comment by martinpelli** [comment]
@DrMoriarty okay I will pass my project, but first of all, how are you doing the installation, I tell you my steps to know if I am missing something.
- I downloaded nativelib and putted Addons folder on root project
- Opened the project and enabled the plugin
- I went to nativlib tab and enabled iOS at the top left (that enabled Android too)
- I installed Firebase Cloud Messaging which installed Core and Analytics too
- I exported my project with Firebase messaging and analytcs enabled from export settings
- I moved my google-services.plist file to the root of my xcode project
- Also I am enabling notifications on capabiliteis just in case

I just tried what you said (you can store your plist in your project addons/nativelib-export/iOS) So I created an nativelib-export/iOS folders because I don´t have it, exported and when running my app it said that I don´t have a plist file

**Comment by DrMoriarty** [comment]
You should not create `nativelib-export/iOS`, in order to use this feature you should install NativeLib-export plugin. It requires by many plugins, so I thought that in common case it already installed.
Yes, your steps looks like my ones.
I was very surprised by your problem because I know this type of issues. They appears when somebody used different firebase frameworks with different versions. But all frameworks was from the one pack and have the same internal versions.
Send me you iOS exported project. I will check all frameworks and maybe I will have an idea what was wrong with them.

**Comment by martinpelli** [comment]
okay can you give me your email so I can share the folder from google drive with you?

**Comment by DrMoriarty** [comment]
drmoriarty.0@gmail.com

**Comment by martinpelli** [comment]
> [drmoriarty.0@gmail.com](mailto:drmoriarty.0@gmail.com)

done

**Comment by DrMoriarty** [comment]
Definitely I should make NativeLib-Export plugin requirement for all other plugins. Among other things, it also add some tricky compilation settings in Xcode project.
If you install it your project will works flawlessly.

**Comment by martinpelli** [comment]
> Definitely I should make NativeLib-Export plugin requirement for all other plugins. Among other things, it also add some tricky compilation settings in Xcode project.
> If you install it your project will works flawlessly.

I installed  nativ lib export and move my plist file to the folder addons/nativelib-export/iOS and when running I keep getting That I don´t have a .plist file on my project, so I move my .plist file to my project and I am getting the same firebase instance id error, maybe nativlib export didn´t installed well?

**Comment by DrMoriarty** [comment]
Did you enable it?
![Снимок экрана 2021-04-28 в 16 09 13](https://user-images.githubusercontent.com/1177068/116409015-1a703f00-a83c-11eb-8896-69b1288700a5.png)

**Comment by martinpelli** [comment]
> Did you enable it?
> ![Снимок экрана 2021-04-28 в 16 09 13](https://user-images.githubusercontent.com/1177068/116409015-1a703f00-a83c-11eb-8896-69b1288700a5.png)

good point.

**Comment by martinpelli** [comment]
@DrMoriarty And finally working!!! thanks dude you are like a hero to me 
![image](https://user-images.githubusercontent.com/63437171/116411997-9eaace00-a80c-11eb-893b-69973dc66477.png)
